# Generated by Django 3.2.5 on 2021-07-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdname', models.CharField(max_length=50)),
                ('pdbody', models.TextField()),
                ('pdimage', models.ImageField(blank=True, null=True, upload_to='product/')),
            ],
        ),
    ]
